# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# To avoid overwriting the output, please code here 
The major difference is:  A vector is a 1-dimensional array that can be either a row vector (1×n) or column vector (n×1). 
A matrix is a 2-dimensional array (n×m) with rows and columns

**2. How to import `NumPy` library?** 

In [4]:
# To avoid overwriting the output, please code here
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [54]:
# To avoid overwriting the output, please code here 
import numpy as np
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
print(f"{arr, type(arr)}")

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [20]:
# To avoid overwriting the output, please code here 
import numpy as np
array = np.arange(6)  
print(f"array({array})")

[0 1 2 3 4 5]


array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros`**

In [10]:
# To avoid overwriting the output, please code here 
import numpy as np
zeros_arr = np.zeros(5)
print(f"array({zeros_arr})")

array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [24]:
# To avoid overwriting the output, please code here 
import numpy as np
matrix = np.zeros((3, 4))  
print(f"array({matrix})")

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [26]:
# To avoid overwriting the output, please code here
import numpy as np
ones_array = np.ones(5)  # Creates array of 5 ones
print(ones_array)

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [17]:
# To avoid overwriting the output, please code here 
import numpy as np
tens_array = np.full(5, 10) 
print(f"array({tens_array})")

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [19]:
# To avoid overwriting the output, please code here 
import numpy as np
even_numbers = np.arange(52, 100, 2) 
print(f"array({even_numbers})")

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [22]:
# To avoid overwriting the output, please code here 
import numpy as np
linspace_array = np.linspace(0, 1, 10)
step_size = linspace_array[1] - linspace_array[0]
print(f"array({linspace_array, step_size})")

(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [24]:
# To avoid overwriting the output, please code here
import numpy as np
vector = np.arange(25)  
print(f"array({vector})")

In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# reshape to convert into 2-d
matrix = vector.reshape(5, 5)  
print(f"array({matrix})")

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
# Using shape
vector.shape = (5, 5)
print(f"array({vector})")
new_matrix = vector.reshape(5, 5)

**12. Please generate the following matrix.**

In [42]:
# To avoid overwriting the output, please code here 
import numpy as np
matrix = np.arange(0.1, 2.6, 0.1).reshape(5, 5)
print(f"array({matrix})")

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [150]:
# To avoid overwriting the output, please code here 
import numpy as np
arr = np.linspace(0, 24, 25, dtype=int)
matrix = arr.reshape(5, 5)
matrix_str = "array([\n" + ",\n".join(
    "    [" + ", ".join(f"{x:2d}" for x in row) + "]"
    for row in matrix
) + "\n])"
print(matrix_str)

array([
    [ 0,  1,  2,  3,  4],
    [ 5,  6,  7,  8,  9],
    [10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19],
    [20, 21, 22, 23, 24]
])


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

linspace(start, stop, num): Generates num equally spaced values between start and stop (inclusive of start).<br> 
arange(start, stop, step): Generates values from start to stop with a specified step size, but the stop value is not included.<br>
arange() takes a step size as the third argument, while linspace() takes the number of points.<br>
In summary, linspace() focuses on the number of elements, while arange() focuses on the step size between elements.

In [ ]:
The main differences are:
   linspace(start, stop, num)`:
   Generates exactly 'num' equally spaced values
   Includes both start and end points by default
   Better for floating-point precision when you know the number of points needed

   arange(start, stop, step):
   Generates values using a fixed step size
   Excludes the stop value (like Python's range())
   More intuitive when you know the step size needed
   Can have floating-point precision issues with steps

**15. How to generate a single random integer number using NumPy built-in function?**

In [66]:
# To avoid overwriting the output, please code here 
import numpy as np
random_int = np.random.randint(0, 210)
print(random_int)

211

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [144]:
# To avoid overwriting the output, please code here 
import numpy as np
random_matrix = np.random.rand(7, 5)
print("[", end="")
for i, row in enumerate(random_matrix):
    print(" [" + " ".join(f"{x:.8f}" for x in row) + "]", end="")
    if i < len(random_matrix) - 1:  
        print(",")
print("\n]")

[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
, [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
, [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
, [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
, [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
, [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
, [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [146]:
# To avoid overwriting the output, please code here 
import numpy as np
identity_matrix = np.identity(5) * 5
output = "array([\n" + ",\n".join(
    " [" + ", ".join(f"{x:.1f}" for x in row) + "]" 
    for row in identity_matrix
) + "\n])"
print(output)

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### I must be feeling comfortable using NumPy now!
# Great Job and Good Luck to me 